# Chapter 2. Python Tools for Data Analysis: Primer to Pandas and NumPy

## Creation and Manipulation with Python data structures

## Appling data analysis operations with combinations of Python data structures

#### Basic data manipulations and computations

In [ ]:
# Finding tasks for data analysis

In [6]:
# Create the lists of dates and closing prices
# Updated lists of dates and closing prices
dates = [
    "2023-08-01", "2023-08-02", "2023-08-03", "2023-08-04",
    "2023-08-07", "2023-08-08", "2023-08-09", "2023-08-10"
]
closing_prices = [
    195.6100, 192.5800, 191.1700, 181.9900,
    178.8500, 179.8000, 178.1900, 177.9700
]

In [ ]:
# Find all prices and dates in closing_prices which is greater than 180
for i in closing_prices:
    if i > 180:
      print(f"The price was {i} on {dates[closing_prices.index(i)]}")

The price was 195.61 on 2023-08-01
The price was 192.58 on 2023-08-02
The price was 191.17 on 2023-08-03
The price was 181.99 on 2023-08-04


In [ ]:
# Find the minimum date and value in the lists
m = min(closing_prices)
ind = closing_prices.index(m)
print(f"The minimum close price was {m:.2f} on {dates[ind]}" )

The minimum close price was 177.97 on 2023-08-10


In [ ]:
# Find which dates are not in the list
for day in range(1, 11):
  if day < 10:
    date = "2023-08-0" + str(day)
  else:
    date = "2023-08-" + str(day)
  if not(date in dates):
    print(f"{date} is not in the collection")

2023-08-05 is not in the collection
2023-08-06 is not in the collection


In [ ]:
# Find the minimum date and value in the dictionary
data_dict = {
    "date":   dates,
    "close":  closing_prices
}
m = min(data_dict["close"])
ind = data_dict["close"].index(m)
m_date = data_dict["date"][ind]
print(f"The minimum close price was {m:.2f} on {m_date}")

The minimum close price was 177.97 on 2023-08-10


In [ ]:
# Filtering tasks for data analysis

In [ ]:
# Create a new list
new_closing_prices = [i for i in closing_prices if i > 180]
print("The list of values > 180:\n", new_closing_prices)

# Find the closing prices where they were either greater than 190 or less than 180
selected_closing_prices = [i for i in closing_prices if i > 190 or i < 180]

print("The list of values > 190 or values < 180:\n", selected_closing_prices)

The list of values > 180:
 [195.61, 192.58, 191.17, 181.99]
The list of values > 190 or values < 180:
 [195.61, 192.58, 191.17, 178.85, 179.8, 178.19, 177.97]


#### Calculating operations for data analysis

In [1]:
%%time
# Create a list of tuples with dates and closing prices
data_tuples = [
    ("2023-08-08", 179.8000), ("2023-08-01", 195.6100),
    ("2023-08-02", 192.5800), ("2023-08-03", 191.1700),
    ("2023-08-04", 181.9900), ("2023-08-07", 178.8500),
    ("2023-08-09", 178.1900), ("2023-08-10", 177.9700)
]
# Sort the data by date (by the first elements of each tuple)
data_tuples.sort()
# Calculate RoR with looping list creating syntax
returns_tuples = [(data_tuples[i][1] - data_tuples[i-1][1]) /
                  data_tuples[i-1][1]
                  for i in range(1, len(data_tuples))]
# Show the RoR by the days
for i in range(len(returns_tuples)):
    print(f"Return on {data_tuples[i+1][0]} is {returns_tuples[i]*100:.2f}%")

Return on 2023-08-02 is -1.55%
Return on 2023-08-03 is -0.73%
Return on 2023-08-04 is -4.80%
Return on 2023-08-07 is -1.73%
Return on 2023-08-08 is 0.53%
Return on 2023-08-09 is -0.90%
Return on 2023-08-10 is -0.12%
CPU times: user 611 µs, sys: 0 ns, total: 611 µs
Wall time: 551 µs


In [ ]:
%timeit returns_tuples = [(data_tuples[i][1] - data_tuples[i-1][1]) / data_tuples[i-1][1] for i in range(1, len(data_tuples))]

2.97 µs ± 863 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [3]:
%%time
# Create a list of dictionaries with dates, open, and close prices
data_dicts = [
    {"date": "2023-08-01", "open": 196.2400, "close": 195.6100},
    {"date": "2023-08-02", "open": 195.0400, "close": 192.5800},
    {"date": "2023-08-03", "open": 191.5700, "close": 191.1700},
    {"date": "2023-08-04", "open": 185.5200, "close": 181.9900},
    {"date": "2023-08-07", "open": 182.1300, "close": 178.8500},
    {"date": "2023-08-08", "open": 179.6900, "close": 179.8000},
    {"date": "2023-08-09", "open": 180.8700, "close": 178.1900},
    {"date": "2023-08-10", "open": 179.4800, "close": 177.9700} ]
# Sort the data by date key
data_dicts.sort(key=lambda x: x["date"])
# Calculate RoR for Close prices
returns_dicts = [(data_dicts[i]["close"] - data_dicts[i-1]["close"]) /
                 data_dicts[i-1]["close"]
                 for i in range(1, len(data_dicts))]
# Show the RoR by the days
for i in range(len(returns_dicts)):
    d = data_dicts[i+1]['date']
    r = returns_dicts[i]
    print(f"Return on {d} for Close prices is {r*100:.2f}%")

Return on 2023-08-02 for Close prices is -1.55%
Return on 2023-08-03 for Close prices is -0.73%
Return on 2023-08-04 for Close prices is -4.80%
Return on 2023-08-07 for Close prices is -1.73%
Return on 2023-08-08 for Close prices is 0.53%
Return on 2023-08-09 for Close prices is -0.90%
Return on 2023-08-10 for Close prices is -0.12%
CPU times: user 4.84 ms, sys: 0 ns, total: 4.84 ms
Wall time: 8.82 ms


In [ ]:
%timeit returns_dicts = [(data_dicts[i]["close"] - data_dicts[i-1]["close"]) / data_dicts[i-1]["close"] for i in range(1, len(data_dicts))]

5.19 µs ± 654 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


## Custom function and Python workflow

In [ ]:
# Simple function
def is_positive(x):
  if x > 0:
    return True
  else:
    return False
print(is_positive(-1))
print(is_positive(0.1))

False
True


In [7]:
# The same and simpler version
def is_positive(x):
    return (x > 0)
print(is_positive(-1))
print(is_positive(0.1))

False
True


In [18]:
# Function with predefined name and numbers of arguments
def mean_for_list(data:list, rnd = 2, sd = False) -> float:
  mean_value = sum(data)/len(data)
  if sd:
    sd_value = ( sum([(x - mean_value)**2 for x in data]) /
                len(data) ) ** 0.5
    return (round(mean_value, rnd),
            round(sd_value, rnd) )
  else:
    return round(mean_value, rnd)
print(mean_for_list(closing_prices, rnd=1))
mean, sd = mean_for_list(closing_prices, sd=True)
print(f"Mean: {mean:.2f}, Standart Deviation: {sd:.2f}")

184.5
Mean: 184.52, Standart Deviation: 6.86


In [1]:
# lambda functions
is_positive = lambda x: x > 0
print(is_positive(-1))  # Output: False
print(is_positive(0.1))  # Output: True

False
True


In [ ]:
print((lambda x: x > 0)(-1))  # Output: False
print((lambda x: x > 0)(0.1))  # Output: True

## NumPy for Data Analysis

In [20]:
import numpy as np

In [21]:
import numpy as np
# 1D NumPy array
dates = np.array([
    "2023-08-01",
    "2023-08-09", # This date is out of place by date sorting
    "2023-08-02", "2023-08-03", "2023-08-04",
    "2023-08-07", "2023-08-08", "2023-08-10",
])
print("The NumPy array for observation dates \n", dates)
# 2D NumPy array. Format: [Open, High, Low, Close]
apple_ohlc = np.array([
    [196.24, 198.00, 195.00, 195.61],  # 1st Aug
    [180.87, 182.00, 178.50, 178.19],  # 9th Aug !
    [195.04, 197.50, 193.00, 192.58],  # 2nd Aug
    [191.57, 192.50, 190.00, 191.17],  # 3rd Aug
    [185.52, 188.00, 184.50, 181.99],  # 4th Aug
    [182.13, 183.40, 178.00, 178.85],  # 7th Aug
    [179.69, 181.50, 178.80, 179.80],  # 8th Aug
    [179.48, 181.00, 177.00, 177.97],]) # 10th Aug
print("2D NumPy array for OHLC data \n", apple_ohlc)

The NumPy array for for observation dates 
 ['2023-08-01' '2023-08-09' '2023-08-02' '2023-08-03' '2023-08-04'
 '2023-08-07' '2023-08-08' '2023-08-10']
2D NumPy array for OHLC data 
 [[196.24 198.   195.   195.61]
 [180.87 182.   178.5  178.19]
 [195.04 197.5  193.   192.58]
 [191.57 192.5  190.   191.17]
 [185.52 188.   184.5  181.99]
 [182.13 183.4  178.   178.85]
 [179.69 181.5  178.8  179.8 ]
 [179.48 181.   177.   177.97]]


In [22]:
# Fetching specific data points using direct indexing
print(dates[1])
print(apple_ohlc[1, 3])
# Accessing non-consecutive dates and their entire OHLC data using list-based indexing
print(dates[[0, 7, 3]])
print(apple_ohlc[[0, 7, 3],:])
# Extracting specific high prices using a combination of row and column indices
print(apple_ohlc[[0, 7, 3],[1]])
# Storing and utilizing indices through a list for reusability and clarity
indices = [0, 3, 7]
print(dates[indices])
print(apple_ohlc[indices])
print(apple_ohlc[indices, 0])
print(apple_ohlc[indices, 3])

2023-08-09
178.19
['2023-08-01' '2023-08-10' '2023-08-03']
[[196.24 198.   195.   195.61]
 [179.48 181.   177.   177.97]
 [191.57 192.5  190.   191.17]]
[198.  181.  192.5]
['2023-08-01' '2023-08-03' '2023-08-10']
[[196.24 198.   195.   195.61]
 [191.57 192.5  190.   191.17]
 [179.48 181.   177.   177.97]]
[196.24 191.57 179.48]
[195.61 191.17 177.97]


In [23]:
sorted_dates = np.sort(dates)
print("Dates sorted in ascending order:\n", sorted_dates)
sorted_date_indices = np.argsort(dates)
print("Indices that would sort 'dates':\n", sorted_date_indices)
apple_ohlc_sorted_by_date = apple_ohlc[sorted_date_indices]
print("OHLC data sorted by 'dates':\n", apple_ohlc_sorted_by_date)
sorted_close_price_indices = np.argsort(apple_ohlc[:, 3])
dates_sorted_by_close_price = dates[sorted_close_price_indices]
print("Dates sorted by Close prices:\n", dates_sorted_by_close_price)

Dates sorted in ascending order:
 ['2023-08-01' '2023-08-02' '2023-08-03' '2023-08-04' '2023-08-07'
 '2023-08-08' '2023-08-09' '2023-08-10']
Indices that would sort 'dates':
 [0 2 3 4 5 6 1 7]
OHLC data sorted by 'dates':
 [[196.24 198.   195.   195.61]
 [195.04 197.5  193.   192.58]
 [191.57 192.5  190.   191.17]
 [185.52 188.   184.5  181.99]
 [182.13 183.4  178.   178.85]
 [179.69 181.5  178.8  179.8 ]
 [180.87 182.   178.5  178.19]
 [179.48 181.   177.   177.97]]
Dates sorted by Close prices:
 ['2023-08-10' '2023-08-09' '2023-08-07' '2023-08-08' '2023-08-04'
 '2023-08-03' '2023-08-02' '2023-08-01']


In [24]:
# Appending new data
new_date = np.array(["2023-08-11"])
new_ohlc = np.array([[180.50, 183.00, 179.50, 182.40]])
sorted_dates = np.append(sorted_dates, new_date)
apple_ohlc_sorted_by_date = np.append(apple_ohlc_sorted_by_date, new_ohlc, axis=0)
# Inserting data at the third position (Index 2)
insert_date = np.array(["2023-08-05"])
insert_ohlc = np.array([[184.20, 185.50, 182.90, 183.30]])
sorted_dates = np.insert(sorted_dates, 2, insert_date)
apple_ohlc_sorted_by_date = np.insert(apple_ohlc_sorted_by_date, 2, insert_ohlc, axis=0)
# Deleting data for the date "2023-08-04" (which is now at Index 3 after insertion)
sorted_dates = np.delete(sorted_dates, 3)
apple_ohlc_sorted_by_date = np.delete(apple_ohlc_sorted_by_date, 3, axis=0)
print("Modified Dates Array:\n", sorted_dates)
print("\nModified OHLC Data:\n", apple_ohlc_sorted_by_date)

Modified Dates Array:
 ['2023-08-01' '2023-08-02' '2023-08-05' '2023-08-04' '2023-08-07'
 '2023-08-08' '2023-08-09' '2023-08-10' '2023-08-11']

Modified OHLC Data:
 [[196.24 198.   195.   195.61]
 [195.04 197.5  193.   192.58]
 [184.2  185.5  182.9  183.3 ]
 [185.52 188.   184.5  181.99]
 [182.13 183.4  178.   178.85]
 [179.69 181.5  178.8  179.8 ]
 [180.87 182.   178.5  178.19]
 [179.48 181.   177.   177.97]
 [180.5  183.   179.5  182.4 ]]


In [ ]:
sorted_dates

apple_ohlc_sorted_by_date

array([[196.24, 198.  , 195.  , 195.61],
       [195.04, 197.5 , 193.  , 192.58],
       [184.2 , 185.5 , 182.9 , 183.3 ],
       [185.52, 188.  , 184.5 , 181.99],
       [182.13, 183.4 , 178.  , 178.85],
       [179.69, 181.5 , 178.8 , 179.8 ],
       [180.87, 182.  , 178.5 , 178.19],
       [179.48, 181.  , 177.  , 177.97],
       [180.5 , 183.  , 179.5 , 182.4 ]])

In [26]:
# Shape Manipulation
transposed_ohlc = apple_ohlc_sorted_by_date.T
print("Transposed OHLC Data:\n", transposed_ohlc)
split_arrays = np.split(transposed_ohlc, 4, axis=0)
print("\nSplitted array is \n", split_arrays)
for idx, arr in enumerate(split_arrays):
    print(f"\nSplit {idx + 1}:\n", arr)
concatenated_data = np.concatenate(split_arrays, axis=1)
print("\nConcatenated Data:\n", concatenated_data)
horizontal_stack = np.hstack(split_arrays[0])
print("\nHorizontally Stacked Open Price Data:\n", horizontal_stack)
vertical_stack = np.vstack(split_arrays)
print("\nVertically Stacked Data:\n", vertical_stack)
reshaped_dates_3x3 = sorted_dates.reshape(3, 3)
print("\nReshaped Dates (3x3):\n", reshaped_dates_3x3)
reshaped_dates_col = sorted_dates.reshape(9, 1)
print("\nReshaped Dates (9x1):\n", reshaped_dates_col)

Transposed OHLC Data:
 [[196.24 195.04 184.2  185.52 182.13 179.69 180.87 179.48 180.5 ]
 [198.   197.5  185.5  188.   183.4  181.5  182.   181.   183.  ]
 [195.   193.   182.9  184.5  178.   178.8  178.5  177.   179.5 ]
 [195.61 192.58 183.3  181.99 178.85 179.8  178.19 177.97 182.4 ]]

Splitted array is 
 [array([[196.24, 195.04, 184.2 , 185.52, 182.13, 179.69, 180.87, 179.48,
        180.5 ]]), array([[198. , 197.5, 185.5, 188. , 183.4, 181.5, 182. , 181. , 183. ]]), array([[195. , 193. , 182.9, 184.5, 178. , 178.8, 178.5, 177. , 179.5]]), array([[195.61, 192.58, 183.3 , 181.99, 178.85, 179.8 , 178.19, 177.97,
        182.4 ]])]

Split 1:
 [[196.24 195.04 184.2  185.52 182.13 179.69 180.87 179.48 180.5 ]]

Split 2:
 [[198.  197.5 185.5 188.  183.4 181.5 182.  181.  183. ]]

Split 3:
 [[195.  193.  182.9 184.5 178.  178.8 178.5 177.  179.5]]

Split 4:
 [[195.61 192.58 183.3  181.99 178.85 179.8  178.19 177.97 182.4 ]]

Concatenated Data:
 [[196.24 195.04 184.2  185.52 182.13 179.69 1

In [28]:
# Find Values and Filtering Operations
date_index = np.where((sorted_dates == "2023-08-04") |
                      (sorted_dates == "2023-08-01"))[0]
print("\ Date index for 2023-08-04 or 2023-08-01:")
print(date_index)
ohlc_on_specific_date = apple_ohlc_sorted_by_date[date_index]
print("\n OHLC data for the specific date:")
print(ohlc_on_specific_date)
highest_close_index = np.argmax(apple_ohlc_sorted_by_date[:, 3])
date_with_highest_close = sorted_dates[highest_close_index]
print("\n Date with the highest close price:")
print(date_with_highest_close)
above_threshold_dates = sorted_dates[apple_ohlc_sorted_by_date[:, 3] > 190]
print("\n Dates with close prices above 190:")
print(above_threshold_dates)
between_threshold_dates = sorted_dates[(apple_ohlc_sorted_by_date[:, 0] < 190) &
                                       (apple_ohlc_sorted_by_date[:, 0] > 180)]
print("\n Dates with open prices between 180 and 190:")
print(between_threshold_dates)


 Date index for 2023-08-04 or 2023-08-01:
[0 3]

 OHLC data for the specific date:
[[196.24 198.   195.   195.61]
 [185.52 188.   184.5  181.99]]

 Date with the highest close price:
2023-08-01

 Dates with close price above 190:
['2023-08-01' '2023-08-02']

 Dates with open price between 180 and 190:
['2023-08-05' '2023-08-04' '2023-08-07' '2023-08-09' '2023-08-11']


In [ ]:
# Arithmetical and Statistical Operations

In [30]:
%time
# Combining results into a single array for display
stats_array = np.array([
    apple_ohlc_sorted_by_date.mean(axis=0),
    np.median(apple_ohlc_sorted_by_date, axis=0),
    np.var(apple_ohlc_sorted_by_date, axis=0),
    np.std(apple_ohlc_sorted_by_date, axis=0)])
print("Statistical measures for OHLC data:\n", stats_array.T)
# Rate of Return calculation
ror_ohlc = (apple_ohlc_sorted_by_date[1:] - apple_ohlc_sorted_by_date[:-1]) / apple_ohlc_sorted_by_date[:-1]
print("Rate of Return for each day:\n", ror_ohlc)
# Logarithmic version of the Rate of Return calculation
ror_ohlc_log = np.log(apple_ohlc_sorted_by_date[1:] / apple_ohlc_sorted_by_date[:-1])
print("Logarithmic version of the Rate of Return for each day:\n", ror_ohlc_log)

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 7.39 µs
Statistical measures for OHLC data:
 [[184.85222222 182.13        36.8959284    6.07420187]
 [186.65555556 183.4         39.29358025   6.26845916]
 [183.02222222 179.5         39.71061728   6.30163608]
 [183.41       181.99        36.29391111   6.02444281]]
Rate of Return for each day:
 [[-0.00611496 -0.00252525 -0.01025641 -0.01549001]
 [-0.05557834 -0.06075949 -0.05233161 -0.04818777]
 [ 0.00716612  0.01347709  0.00874795 -0.00714675]
 [-0.01827296 -0.02446809 -0.03523035 -0.0172537 ]
 [-0.01339702 -0.01035987  0.00449438  0.00531171]
 [ 0.00656687  0.00275482 -0.00167785 -0.00895439]
 [-0.00768508 -0.00549451 -0.00840336 -0.00123464]
 [ 0.00568308  0.01104972  0.01412429  0.02489184]]
Logarithmic version of the Rate of Return for each day:
 [[-0.00613373 -0.00252845 -0.01030937 -0.01561123]
 [-0.05718254 -0.0626837  -0.05375063 -0.0493875 ]
 [ 0.00714057  0.01338708  0.00870991 -0.00717241]
 [-0.01844198 -0.0247724  -0.

In [31]:
close_prices = apple_ohlc_sorted_by_date[:, 3]
%timeit ror = (close_prices[1:] - close_prices[:-1]) / close_prices[:-1]

1.92 µs ± 479 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [32]:
is_positive_v = np.vectorize(is_positive)

print(is_positive_v(ror_ohlc))

[[False False False False]
 [False False False False]
 [ True  True  True False]
 [False False False False]
 [False False  True  True]
 [ True  True False False]
 [False False False False]
 [ True  True  True  True]]


## Working with Pandas for Data Analysis

In [33]:
import numpy as np
import pandas as pd

In [ ]:
dates = np.array([
    "2023-08-01", "2023-08-09", "2023-08-02",
    "2023-08-03", "2023-08-04", "2023-08-07",
    "2023-08-08", "2023-08-10",
])

apple_ohlc = np.array([
    [196.24, 198.00, 195.00, 195.61],  # 1st Aug
    [180.87, 182.00, 178.50, 178.19],  # 9th Aug !
    [195.04, 197.50, 193.00, 192.58],  # 2nd Aug
    [191.57, 192.50, 190.00, 191.17],  # 3rd Aug
    [185.52, 188.00, 184.50, 181.99],  # 4th Aug
    [182.13, 183.40, 178.00, 178.85],  # 7th Aug
    [179.69, 181.50, 178.80, 179.80],  # 8th Aug
    [179.48, 181.00, 177.00, 177.97],  # 10th Aug
])

ds = pd.Series(apple_ohlc[:,3], index=dates, name='Close Prices')
print("Series is \n", ds)

df = pd.DataFrame(apple_ohlc, index=dates,
                  columns=["Open", "High", "Low", "Close"])
print("\nDataFrame is \n", df)

Series is 
 2023-08-01    195.61
2023-08-09    178.19
2023-08-02    192.58
2023-08-03    191.17
2023-08-04    181.99
2023-08-07    178.85
2023-08-08    179.80
2023-08-10    177.97
Name: Close Prices, dtype: float64

DataFrame is 
               Open   High    Low   Close
2023-08-01  196.24  198.0  195.0  195.61
2023-08-09  180.87  182.0  178.5  178.19
2023-08-02  195.04  197.5  193.0  192.58
2023-08-03  191.57  192.5  190.0  191.17
2023-08-04  185.52  188.0  184.5  181.99
2023-08-07  182.13  183.4  178.0  178.85
2023-08-08  179.69  181.5  178.8  179.80
2023-08-10  179.48  181.0  177.0  177.97


In [ ]:
# Selecting Values and Slicing Datasets
# Series Selection
print("The first element in the Series is: ",
      ds.iloc[0])
print("\nThe elements from index 1 to 2 in the Series are: \n",
      ds[1:3])
print("\nThe element in the Series at index '2023-08-02' is: ",
      ds["2023-08-02"])
print("\nThe elements in the Series from '2023-08-09' to '2023-08-04' are: \n",
      ds["2023-08-09":"2023-08-04"])
# DataFrame Selection
print("The 'Open' column from the DataFrame is: \n",
      df["Open"])
print("\nThe 'Open' and 'Close' columns from the DataFrame are: \n",
      df[["Open", "Close"]])
print("\nThe 'Close' column values between indexes '2023-08-09' and '2023-08-04' are: \n",
      df.loc["2023-08-09":"2023-08-04", "Close"])
print("\nAll column values between '2023-08-09' and '2023-08-04' are: \n",
      df.loc["2023-08-09":"2023-08-04", :])
print("\nThe value at the second row and the third column is: ",
      df.iloc[1, 2])
print("\nThe values from the second and fourth rows, excluding the last column, are: \n",
      df.iloc[[1, 3], :-1])

The first element in the Series is:  195.61

The elements from index 1 to 2 in the Series are: 
 2023-08-09    178.19
2023-08-02    192.58
Name: Close Prices, dtype: float64

The element in the Series at index '2023-08-02' is:  192.58

The elements in the Series from '2023-08-09' to '2023-08-04' are: 
 2023-08-09    178.19
2023-08-02    192.58
2023-08-03    191.17
2023-08-04    181.99
Name: Close Prices, dtype: float64
The 'Open' column from the DataFrame is: 
 2023-08-01    196.24
2023-08-09    180.87
2023-08-02    195.04
2023-08-03    191.57
2023-08-04    185.52
2023-08-07    182.13
2023-08-08    179.69
2023-08-10    179.48
Name: Open, dtype: float64

The 'Open' and 'Close' columns from the DataFrame are: 
               Open   Close
2023-08-01  196.24  195.61
2023-08-09  180.87  178.19
2023-08-02  195.04  192.58
2023-08-03  191.57  191.17
2023-08-04  185.52  181.99
2023-08-07  182.13  178.85
2023-08-08  179.69  179.80
2023-08-10  179.48  177.97

The 'Close' column values between ind

In [ ]:
# Dataset Filtering
# Series
print("Elements in Series > 190: \n",
      ds > 190)
print("\nSeries where elements > 190: \n",
      ds[ds > 190])
print("\nSeries element at index '2023-08-03': \n",
      ds[ds.index == "2023-08-03"])
# DataFrame
print("\nDataFrame where 'Open' > 190 and 'Close' < 192: \n",
      df[(df['Open'] > 190) & (df['Close'] < 192)])
print("\nDataFrame where 'Open' is greater than 'Close': \n",
      df[df['Open'] > df['Close']])
print("\nDataFrame where 'Close' is in [192.58, 178.19]: \n",
      df[df['Close'].isin([192.58, 178.19])])
print("\nDataFrame at index '2023-08-03': \n",
      df[df.index == "2023-08-03"])
print("\nDataFrame at indices ['2023-08-03','2023-08-09']: \n",
      df[df.index.isin(["2023-08-03", "2023-08-09"])])

# Combining Conditions
print("\nDataFrame where 'Open' > 180, 'Open' < 190, and 'Close' != 181.99: \n",
      df[(df['Open'] > 180) & (df['Open'] < 190) & (df['Close'] != 181.99)])

# Creating a sub-dataframe for the date range and applying the condition
subset_df = df.loc["2023-08-01":"2023-08-08"]
print("\nSubset DataFrame where 'Open' > 180, 'Open' < 190, and 'Close' != 181.99: \n",
      subset_df[(subset_df['Open'] > 180) & (subset_df['Open'] < 190) & (subset_df['Close'] != 181.99)])


Elements in Series > 190: 
 2023-08-01     True
2023-08-09    False
2023-08-02     True
2023-08-03     True
2023-08-04    False
2023-08-07    False
2023-08-08    False
2023-08-10    False
Name: Close Prices, dtype: bool

Series where elements > 190: 
 2023-08-01    195.61
2023-08-02    192.58
2023-08-03    191.17
Name: Close Prices, dtype: float64

Series element at index '2023-08-03': 
 2023-08-03    191.17
Name: Close Prices, dtype: float64

DataFrame where 'Open' > 190 and 'Close' < 192: 
               Open   High    Low   Close
2023-08-03  191.57  192.5  190.0  191.17

DataFrame where 'Open' is greater than 'Close': 
               Open   High    Low   Close
2023-08-01  196.24  198.0  195.0  195.61
2023-08-09  180.87  182.0  178.5  178.19
2023-08-02  195.04  197.5  193.0  192.58
2023-08-03  191.57  192.5  190.0  191.17
2023-08-04  185.52  188.0  184.5  181.99
2023-08-07  182.13  183.4  178.0  178.85
2023-08-10  179.48  181.0  177.0  177.97

DataFrame where 'Close' is in [192.58, 1

In [ ]:
# Insertion and Deletion of Data
# For Series
ds_new = pd.Series(data=[177.79, 179.46],
                   index=["2023-08-11", "2023-08-14"],
                   name=ds.name)
ds = pd.concat([ds, ds_new]) # method is deprecated
print("Modified Series (showing last 3 entries):\n", ds.tail(3))
ds["2023-08-11"] = 177.32
print("Series after value change (showing last 3 entries):\n", ds.tail(3))

ds = ds.drop(labels=["2023-08-11", "2023-08-14"])
print("\nSeries after Deletion (showing last 3 entries):\n", ds.tail(3))

# For DataFrame
df.loc["2023-08-11"] = [177.32, 178.62, 176.55, 177.79]
print("\nModified DataFrame (showing last 3 entries):\n", df.tail(3))

new_df = pd.DataFrame(data=[[177.32, 178.62, 176.55, 177.79],
                            [177.97, 179.69, 177.31, 179.46]],
                      index=["2023-08-11", "2023-08-14"],
                      columns=df.columns)
df = pd.concat([df, new_df]) # method is deprecated
print("\nModified DataFrame (showing last 5 entries):\n", df.tail())

df = df.drop(labels=["2023-08-11"], axis=0)
print("\nDataFrame after Deletion (showing last 3 entries):\n", df.tail(3))

df.drop(labels=["2023-08-14"], axis=0, inplace=True)
print("\nDataFrame after Deletion (showing last 3 entries):\n", df.tail(3))

print("\nDataFrame after Deletion two Columns (showing first 3 entries):\n",
      df.drop(labels=["High", "Low"], axis=1).head(3))

Modified Series (showing last 3 entries):
 2023-08-10    177.97
2023-08-11    177.79
2023-08-14    179.46
Name: Close Prices, dtype: float64
Series after value change (showing last 3 entries):
 2023-08-10    177.97
2023-08-11    177.32
2023-08-14    179.46
Name: Close Prices, dtype: float64

Series after Deletion (showing last 3 entries):
 2023-08-07    178.85
2023-08-08    179.80
2023-08-10    177.97
Name: Close Prices, dtype: float64

Modified DataFrame (showing last 3 entries):
               Open    High     Low   Close
2023-08-08  179.69  181.50  178.80  179.80
2023-08-10  179.48  181.00  177.00  177.97
2023-08-11  177.32  178.62  176.55  177.79

Modified DataFrame (showing last 5 entries):
               Open    High     Low   Close
2023-08-08  179.69  181.50  178.80  179.80
2023-08-10  179.48  181.00  177.00  177.97
2023-08-11  177.32  178.62  176.55  177.79
2023-08-11  177.32  178.62  176.55  177.79
2023-08-14  177.97  179.69  177.31  179.46

DataFrame after Deletion (showing l

In [ ]:
# Resetting and setting the index
df_reset = df.reset_index()
print("\nDataFrame after resetting the index:\n",
      df_reset.head(3))

# Renaming the 'index' column to 'Date'
df_reset = df_reset.rename(columns={'index': 'Date'})
print("\nDataFrame after renaming the 'index' column to 'Date':\n",
      df_reset.head(3))

# Setting 'Date' as the index of the DataFrame
df_reset = df_reset.set_index('Date')
print("\nDataFrame after Reindexing with 'Date':\n",
      df_reset.head(3))

# Preparing DataFrames for Join operation
# Dropping rows with index '2023-08-10' and '2023-08-01'
df_reset.drop(labels=["2023-08-10", "2023-08-01"], axis=0, inplace=True)

# Dropping 'Open', 'High', 'Low' columns
df_reset.drop(labels=["Open", "High", "Low"], axis=1, inplace=True)

# Performing Join operations
# Right join keeps every row from the right DataFrame, and drops the unmatched rows from the left DataFrame.
print("\nDataFrame after Right Join:\n",
      df_reset.join(df, how="right", lsuffix='_left', rsuffix='_right'))

# Left join keeps every row from the left DataFrame, and drops the unmatched rows from the right DataFrame.
print("\nDataFrame after Left Join:\n",
      df_reset.join(df, how="left", lsuffix='_left', rsuffix='_right'))

# Sort Operations
# Sorting DataFrame by 'Open' column values in descending order
df_sorted = df.sort_values(by='Open', ascending=False)
print("\nDataFrame sorted by 'Open' values in descending order:\n",
      df_sorted.head(3))

# Sorting DataFrame by Index in ascending order (default)
df_sorted = df.sort_index()
print("\nDataFrame sorted by Index in ascending order:\n",
      df_sorted.head(3))


DataFrame after resetting the index:
         index    Open   High    Low   Close
0  2023-08-01  196.24  198.0  195.0  195.61
1  2023-08-09  180.87  182.0  178.5  178.19
2  2023-08-02  195.04  197.5  193.0  192.58

DataFrame after renaming the 'index' column to 'Date':
          Date    Open   High    Low   Close
0  2023-08-01  196.24  198.0  195.0  195.61
1  2023-08-09  180.87  182.0  178.5  178.19
2  2023-08-02  195.04  197.5  193.0  192.58

DataFrame after Reindexing with 'Date':
               Open   High    Low   Close
Date                                    
2023-08-01  196.24  198.0  195.0  195.61
2023-08-09  180.87  182.0  178.5  178.19
2023-08-02  195.04  197.5  193.0  192.58

DataFrame after Right Join:
             Close_left    Open   High    Low  Close_right
2023-08-01         NaN  196.24  198.0  195.0       195.61
2023-08-09      178.19  180.87  182.0  178.5       178.19
2023-08-02      192.58  195.04  197.5  193.0       192.58
2023-08-03      191.17  191.57  192.5  190.

In [ ]:
# Calculated values and creating new features
df_sorted['Price_Diff'] = df_sorted['High'] - df_sorted['Low']
df_sorted['Log_Close'] = np.log(df_sorted['Close'])
df_sorted['RoR'] = df_sorted['Close'].pct_change() * 100
df_sorted['Log_RoR'] = np.log(df_sorted['Close'] / df_sorted['Close'].shift(1))
df_sorted['RoR_Status'] = df_sorted['RoR'].apply(is_positive)
df_sorted['Cum_Prod_RoR'] = ((1 + df_sorted['RoR'] / 100).cumprod() - 1) * 100
df_sorted['Cum_Prod_Log_RoR'] = (1 + df_sorted['Log_RoR']).cumprod() - 1
print("\nDataFrame after calculating the Cumulative Product for RoR and Log_RoR:\n",
      df_sorted)


DataFrame after calculating the Cumulative Product for RoR and Log_RoR:
               Open   High    Low   Close  Price_Diff  Log_Close       RoR  \
2023-08-01  196.24  198.0  195.0  195.61         3.0   5.276123       NaN   
2023-08-02  195.04  197.5  193.0  192.58         4.5   5.260512 -1.549001   
2023-08-03  191.57  192.5  190.0  191.17         2.5   5.253163 -0.732163   
2023-08-04  185.52  188.0  184.5  181.99         3.5   5.203952 -4.802009   
2023-08-07  182.13  183.4  178.0  178.85         5.4   5.186547 -1.725370   
2023-08-08  179.69  181.5  178.8  179.80         2.7   5.191845  0.531171   
2023-08-09  180.87  182.0  178.5  178.19         3.5   5.182850 -0.895439   
2023-08-10  179.48  181.0  177.0  177.97         4.0   5.181615 -0.123464   

             Log_RoR  RoR_Status  Cum_Prod_RoR  Cum_Prod_Log_RoR  
2023-08-01       NaN       False           NaN               NaN  
2023-08-02 -0.015611       False     -1.549001         -0.015611  
2023-08-03 -0.007349       Fals

## &copy; Dr. Dmytro Zherlitsyn, 2023 <br>
## &copy; BPB Publications, 2023